### ISSUE TITLE
java.lang.IllegalArgumentException when try to set-device-owner

### ISSUE THREAD

**Issue by combrs** [x13a/Sentry#16]
Why this can occur?

/$ adb root
restarting adbd as root
/$ adb shell
X00TD:/ # dpm set-device-owner me.lucky.sentry/.DeviceAdminReceiver
```
Exception occurred while executing 'set-device-owner':
java.lang.IllegalArgumentException: Unknown admin: ComponentInfo{me.lucky.sentry/me.lucky.sentry.DeviceAdminReceiver}
        at com.android.server.devicepolicy.DevicePolicyManagerService.findAdmin(DevicePolicyManagerService.java:2950)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setActiveAdmin(DevicePolicyManagerService.java:3461)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:256)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:89)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:9845)
        at android.os.Binder.shellCommand(Binder.java:950)
        at android.os.Binder.onTransact(Binder.java:834)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6984)
        at android.os.Binder.execTransactInternal(Binder.java:1184)
        at android.os.Binder.execTransact(Binder.java:1143)

```
Phone properties:
[ro.product.system.brand]: [asus]
[ro.product.system.device]: [X00TD]
[ro.product.system.manufacturer]: [asus]
[ro.product.system.model]: [Zenfone Max Pro M1]
[ro.product.system.name]: [lineage_X00TD]
[ro.system.build.fingerprint]: [asus/WW_X00TD/ASUS_X00T_2:8.1.0/OPM1/15.2016.1805.318-20180712:user/release-keys]
[ro.system.build.id]: [SQ3A.220705.004]
[ro.system.build.type]: [userdebug]
[ro.system.build.version.release_or_codename]: [12]
[ro.system.build.version.sdk]: [32]
[ro.system.product.cpu.abilist64]: [arm64-v8a]

**Comment by x13a** [comment]
Because I have moved _DeviceAdminReceiver_ and forgot to update documentation.

```sh
adb shell dpm set-device-owner me.lucky.sentry/.admin.DeviceAdminReceiver
```

**Comment by x13a** [comment]
Be aware to set device owner your device have to be clean (without accounts). To remove device owner you will have to do a factory reset.

**Comment by combrs** [comment]
> Be aware to set a device owner your device have to be clean (without accounts). To remove device owner you will have to do a factory reset.

I have some accounts - davx5, google, telegram, nextcloud, etc. If I set device-owner as above (to block usb) what will happen?

**Comment by x13a** [comment]
You can try, but as I remember, Android will not allow you to do it. An error you will get.

**Comment by x13a** [comment]
Closing on inactivity

**Comment by combrs** [comment]
> You can try, but as I remember, Android will not allow you to do it. An error you will get.

yes, there is error
```
Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.
```
Then usb control ("disable USB data connections")  can be applied only for clean device without accounts.

**Comment by x13a** [comment]
You can try, but as I remember, Android will not allow you to do it. Error
you will get.
